LangString addOrReinstall ${LANG_ENGLISH} "Add or reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Choose the action you want to perform and click Next to continue."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running. Close it and try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is running.$\nClick OK to terminate it."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose the maintenance action to perform."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how ${PRODUCTNAME} should be installed."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Do not uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (this installer does not allow downgrades without uninstalling first)"
LangString failedToKillApp ${LANG_ENGLISH} "Unable to terminate {{product_name}}. Close it manually and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed on this system. Installing an older version is not recommended. If you still want to install it, uninstall the current version first. Choose the action to perform and click Next to continue."
LangString older ${LANG_ENGLISH} "Older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "${PRODUCTNAME} version $R4 is already installed on this system. We recommend uninstalling the current version before continuing. Choose the action to perform and click Next to continue."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled by this installer, so silent installation cannot continue.$\nUse the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "Unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 installation failed. The app cannot run without WebView2. Restart the installer and try again."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: failed to download WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "The WebView2 bootstrapper was downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading the WebView2 bootstrapper..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: WebView2 installation failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed successfully"
LangString deleteAppData ${LANG_ENGLISH} "Delete app data"
LangString languageSelectorTitle ${LANG_ENGLISH} "DesktopGo Installer Language"
LangString languageSelectorText ${LANG_ENGLISH} "Select the language for the installation wizard."
LangString muiWelcomePageText ${LANG_ENGLISH} "This wizard will guide you through the installation of $(^NameDA).$\r$\n$\r$\nBefore installing, we recommend closing related applications to avoid file conflicts and reduce the chance that a restart will be required after installation.$\r$\n$\r$\n$_CLICK"
LangString everythingInstallerMissing ${LANG_ENGLISH} "The bundled Everything installer could not be found.$\r$\nSearch will remain unavailable until Everything is installed."
LangString everythingPageTitle ${LANG_ENGLISH} "Search component"
LangString everythingPageSubtitle ${LANG_ENGLISH} "Choose whether to install Everything"
LangString everythingPageDescription ${LANG_ENGLISH} "DesktopGo file search currently supports the installed version of Everything only."
LangString everythingDetectedDescription ${LANG_ENGLISH} "An installed version of Everything was detected, so this step will be skipped automatically."
LangString everythingInstallCheckbox ${LANG_ENGLISH} "Install Everything"
LangString everythingNotDetectedDescription ${LANG_ENGLISH} "No installed version of Everything was detected. You can install it together with DesktopGo."
LangString everythingInstallRecommendedCheckbox ${LANG_ENGLISH} "Install Everything (Recommended)"
LangString everythingSearchUnavailableNotice ${LANG_ENGLISH} "If you clear this option, search will not be available after DesktopGo is installed."
LangString installLanguageCode ${LANG_ENGLISH} "en"
