LangString addOrReinstall ${LANG_SIMPCHINESE} "添加或重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择要执行的操作，然后点击“下一步”继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！请先关闭它，然后重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n点击“确定”以结束它。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装器不允许在不卸载的情况下执行降级安装）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法结束 {{product_name}}。请先关闭它，然后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "系统中已经安装了更新版本的 ${PRODUCTNAME}！不建议安装较旧版本。如果你确实要安装旧版本，建议先卸载当前版本。请选择要执行的操作，然后点击“下一步”继续。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装 $R4 版本的 ${PRODUCTNAME}。建议在安装前先卸载当前版本。请选择要执行的操作，然后点击“下一步”继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装器已禁用降级安装，无法继续执行静默安装。请改用图形界面安装器。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前先卸载"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "安装 WebView2 失败！应用无法在缺少 WebView2 的情况下运行。请尝试重新启动安装器。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：下载 WebView2 失败 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 引导安装程序下载成功"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导安装程序..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 失败，退出代码为 $1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装成功"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除应用数据"
LangString languageSelectorTitle ${LANG_SIMPCHINESE} "DesktopGo 安装语言"
LangString languageSelectorText ${LANG_SIMPCHINESE} "请选择安装向导使用的语言。"
LangString muiWelcomePageText ${LANG_SIMPCHINESE} "此程序将引导你完成 $(^NameDA) 的安装。$\r$\n$\r$\n安装前，建议先关闭正在运行的相关程序，以避免文件被占用，并减少安装后需要重新启动计算机的可能性。$\r$\n$\r$\n$_CLICK"
LangString everythingInstallerMissing ${LANG_SIMPCHINESE} "未找到随 DesktopGo 打包的 Everything 安装程序。$\r$\n搜索功能在安装 Everything 前不可用。"
LangString everythingPageTitle ${LANG_SIMPCHINESE} "搜索组件"
LangString everythingPageSubtitle ${LANG_SIMPCHINESE} "选择是否安装 Everything"
LangString everythingPageDescription ${LANG_SIMPCHINESE} "DesktopGo 的文件搜索仅支持安装版 Everything。"
LangString everythingDetectedDescription ${LANG_SIMPCHINESE} "已检测到安装版 Everything，本次安装将自动跳过该步骤。"
LangString everythingInstallCheckbox ${LANG_SIMPCHINESE} "安装 Everything"
LangString everythingNotDetectedDescription ${LANG_SIMPCHINESE} "未检测到安装版 Everything。你可以在安装 DesktopGo 时一并安装。"
LangString everythingInstallRecommendedCheckbox ${LANG_SIMPCHINESE} "安装 Everything（推荐）"
LangString everythingSearchUnavailableNotice ${LANG_SIMPCHINESE} "如果取消勾选，DesktopGo 安装后搜索功能将不可用。"
LangString installLanguageCode ${LANG_SIMPCHINESE} "zh"
